### ISSUE TITLE
Bom dia, Giulerme

### ISSUE THREAD

**Issue by ewurch** [vogtguilherme/vogtguilherme.github.io#1]
Achei esse o lugar mais conveniente para compartilhar contigo este framework que acho que tu vai ter interesse

[https://github.com/azac/cobol-on-wheelchair](https://github.com/azac/cobol-on-wheelchair)

Grande abraço e saludos desde Países Bajos!

**Comment by ewurch** [comment]
giulerme nao se interessou

**Comment by vogtguilherme** [comment]
Prezado Sr ewurch,

Peço perdão pela demora em respondê-lo. Eu já havia visto sua mensagem e apreciado o conteúdo dela, porém esqueci de retornar o quão gratificante foi para mim conhecer este framework. Aliás, expressei um pouco desta alegria [neste post do X](https://twitter.com/votconta/status/1717370240521167181)

Espero que a vida esteja harmoniosa nas terras inferiores. E por favor continue a compartilhar frameworks e ferramentas interessantes que encontrares em cobol.

Grande abraço paracatuense
